#!/bin/bash
if [[ $(uname) == "Darwin" ]]; then
	clang++ -std=gnu++20 -O3 -Wall -Werror ping_pong.cpp -o ping_pong \
		-I/opt/homebrew/opt/sfml/include \
		-L/opt/homebrew/opt/sfml/lib \
		-lsfml-window -lsfml-graphics -lsfml-system
elif [[ $(uname) == "linux" ]]; then
	g++ -std=gnu++20 -O3 -Wall -Werror ping_pong.cpp -o ping_pong \
		-lsfml-window -lsfml-graphics -lsfml-system
else
	echo "Unknown system!" 1>&2
	exit 1
fi